### ISSUE TITLE
Upgrade the Navigation CLI samples to bootstrap 4

### ISSUE THREAD

**Issue by adriatic** [longarone/code-samples#3]
Using the new **[navbar](https://getbootstrap.com/docs/4.0/components/navbar/)** component is of particular interest in all identity management situations, where the "content" of the navbar viewed as the container of navbar items, is the function of the application state.

Since Aurelia framework _still_ does not have its own UI components, I would like to use every UI component available  from Bootstrap 4 in all our samples that are declared to be "Boostrap based".

**Comment by adriatic** [comment]
### Started withe the **[esnext](https://github.com/longarone/code-samples/tree/master/basic/esnext)** sample:
 
I got stuck with the changes that need to be applied to the **[navbar.html](https://github.com/longarone/code-samples/blob/master/basic/esnext/src/nav-bar.html)** code in order to make it Botstrap 4 navbar component compatible. After a bit of searching I found **[this PR](https://github.com/aurelia/skeleton-navigation/pull/874/commits/37070dc2053b5092b3117e3ed5e6f65383edfa81)** - which has not been merged yet, so I changed (locally) the code by looking at the PR's diffs. This is a risky proposition as it is easy to miss something (or the PR is not really tested sufficiently 😢).

With all mods from this PR the "patched" esnext app fails with:

```
INFO [aurelia] Aurelia Started
popper.js:1 Unhandled rejection TypeError: this.sourceExpression.connect is not a function
    at Binding.connect (http://localhost:9000/scripts/vendor-bundle.js:11002:29)
    at enqueueBindingConnect (http://localhost:9000/scripts/vendor-bundle.js:6195:15)
    at Binding.bind (http://localhost:9000/scripts/vendor-bundle.js:10967:9)
    at Controller.bind (http://localhost:9000/scripts/vendor-bundle.js:22737:19)
    at View.bind (http://localhost:9000/scripts/vendor-bundle.js:20756:24)
    at Controller.bind (http://localhost:9000/scripts/vendor-bundle.js:22759:19)
    at Controller.automate (http://localhost:9000/scripts/vendor-bundle.js:22704:12)
    at http://localhost:9000/scripts/vendor-bundle.js:23849:20
From previous event:
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/scripts/vendor-bundle.js:23848:45)
    at CompositionEngine.compose (http://localhost:9000/scripts/vendor-bundle.js:23934:21)
    at TemplatingEngine.compose (http://localhost:9000/scripts/vendor-bundle.js:24197:38)
    at Aurelia.setRoot (http://localhost:9000/scripts/vendor-bundle.js:12874:21)
    at http://localhost:9000/scripts/app-bundle.js:388:22
From previous event:
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:387:21)
    at http://localhost:9000/scripts/vendor-bundle.js:11703:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11698:56)
    at http://localhost:9000/scripts/vendor-bundle.js:11734:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:11733:26)
    at http://localhost:9000/scripts/vendor-bundle.js:11720:9
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11715:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11740:37)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5484:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4671:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4964:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5345:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4949:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3922:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3847:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4901:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4576:26)
``` 

_some data from this crash omited_

**Comment by adriatic** [comment]
Fixed - thanks to @bigopon 👏

**Comment by adriatic** [comment]
Finished with navigation skeletons from the **[basic](https://github.com/longarone/code-samples/tree/master/basic)** set.

Still need to update these same samples in other categories.
